<?php
if($this->isCustomerLoggedIn()){
	$randomNumber = rand(1, 1/*$this->getDensity()*/);
	if($randomNumber == 1){
		$eggs = $this->getEggs();
		foreach($eggs as $egg){
			echo '<img data-egg="' . $egg . '" style="width:' . $this->getWidth() . 'px; height:' . $this->getheight() . 'px;"  src="' . $this->getImageUrl($egg) . '">';
		}
	}
}
?>
<script type="text/javascript">
require(
    [
        'jquery',
        'domReady!'
    ],
    function ($) {
    	var images = "<?php echo $this->getImages(); ?>";
    	images = images.split(",");
    	for(var i=0 ; i<images.length ; i++){
			document.body.innerHTML = document.body.innerHTML.replace('[egg id="'+i+'"]', '<span class="easter-cntr" data-id="'+i+'"><img style="width:<?php echo $this->getWidth(); ?>px; height:<?php echo $this->getheight(); ?>px;" src="/pub/media/eastereggs/'+images[i]+'"></span>');
		}
		
    }
);
</script>
<style type="text/css">
	.easter-cntr{
		cursor: pointer;
	}
	.easter-cntr img{
		
	}
</style>