<form id="saveeggcus" action="/eastereggs/easteregg/saveeggcus/">
	<?= $block->getBlockHtml('formkey') ?>
	<input type="hidden" name="egg_id" id="egg_id">
</form>
<div id="popup-eggs-back" style="display: none;"></div>
<div class="popup-eggs" id="popup-modal-foundanegg" style="display: none;" >
	<div class="header"><?php echo $this->getFoundEggsTitle(); ?></div>
	<div class="body"></div>
	<span class="close">Ok</span>
</div>
<div class="popup-eggs" id="popup-modal-foundalleggs" style="display: none;">
	<div class="header"><?php echo $this->getFoundAllEggsTitle(); ?></div>
	<div class="body"></div>
	<span class="close">Ok</span>
</div>
<div class="popup-eggs" id="popup-modal-notloggedin" style="display: none;">
	<div class="header"><?php echo $this->getNotLoggedInUsersTitle(); ?></div>
	<div class="body"><?php echo $this->getNotLoggedInUsersMessage(); ?></div>
	<span class="close">Ok</span>
</div>
<script type="text/javascript">
require([
        'jquery',
        'Magento_Ui/js/modal/modal',
        'domReady!'
    ],function ($, modal) {

    	var allEggs = "<?php echo $this->getImages();?>";
    	var savedEggs = "<?php echo $this->getSavedEggs();?>";
    	var couponCode = "<?php echo $this->getCouponCode();?>";
    	var redirectUrl = "<?php echo $this->getRedirectUrl();?>";


    	$(".popup-eggs .close").on( "click", function() {
  			$(this).parent().first().hide();
    		$('#popup-eggs-back').hide();
		});
		$("#popup-modal-foundalleggs .close").on( "click", function() {
  			window.location.replace(redirectUrl);
		});


    	allEggs = allEggs.split(",");
    	savedEggs = savedEggs.split(",");
    	var allEggsHtml ='';
    	for(var i=0 ; i<allEggs.length ; i++){
    		var exist = false;
    		for(var j=0 ; j<savedEggs.length ; j++){
    			if((savedEggs[j]!=="") && (savedEggs[j] == i)){
    				exist = true;
    			}
    		}
    		if(exist){
    			if($('#description .product.attribute.description .value').length){
    				$('#description .product.attribute.description .value').first().html($('#description .product.attribute.description .value').first().html().replace('[egg id="'+i+'"]', ''));
    			}
    			if($('.column.main').length){
    				$('.column.main').first().html($('.column.main').first().html().replace('[egg id="'+i+'"]', ''));
    			}
    			$('.block').each(function( index ) {
				  	$(this).html($(this).html().replace('[egg id="'+i+'"]', ''));
				});
				if($('.page-title-wrapper').length){
    				$('.page-title-wrapper').first().html($('.page-title-wrapper').first().html().replace('[egg id="'+i+'"]', ''));
    			}
				
    		}else{
    			if($('#description .product.attribute.description .value').length){
    				$('#description .product.attribute.description .value').first().html($('#description .product.attribute.description .value').first().html().replace('[egg id="'+i+'"]', '<span class="easter-cntr" data-id="'+i+'"><img style="width:<?php echo $this->getWidth(); ?>px; height:<?php echo $this->getheight(); ?>px;" src="/pub/media/eastereggs/'+allEggs[i]+'"></span>'));
    			}
    			if($('.column.main').length){
    				$('.column.main').first().html($('.column.main').first().html().replace('[egg id="'+i+'"]', '<span class="easter-cntr" data-id="'+i+'"><img style="width:<?php echo $this->getWidth(); ?>px; height:<?php echo $this->getheight(); ?>px;" src="/pub/media/eastereggs/'+allEggs[i]+'"></span>'));
    			}
    			$('.block').each(function( index ) {
				  	$(this).html($(this).html().replace('[egg id="'+i+'"]', '<span class="easter-cntr" data-id="'+i+'"><img style="width:<?php echo $this->getWidth(); ?>px; height:<?php echo $this->getheight(); ?>px;" src="/pub/media/eastereggs/'+allEggs[i]+'"></span>'));
				});
				if($('.page-title-wrapper').length){
    				$('.page-title-wrapper').first().html($('.page-title-wrapper').first().html().replace('[egg id="'+i+'"]', '<span class="easter-cntr" data-id="'+i+'"><img style="width:<?php echo $this->getWidth(); ?>px; height:<?php echo $this->getheight(); ?>px;" src="/pub/media/eastereggs/'+allEggs[i]+'"></span>'));
    			}
    		}
    		
    		allEggsHtml+='<img style="width:<?php echo $this->getWidth(); ?>px; height:<?php echo $this->getheight(); ?>px;" src="/pub/media/eastereggs/'+allEggs[i]+'">';
		}
		$('.easter-cntr').click(function(){
			var currentElement = $(this);
			var eggImage = currentElement.html();
			<?php
			if($this->isCustomerLoggedIn()){
				?>
				$('#egg_id').val($(this).data('id'));
				$.ajax({
		            url: "/eastereggs/easteregg/saveeggcus/",
		            type: "POST",
		            data: $('form#saveeggcus').serialize(),
		            showLoader: true,
		            success: function (response) {
                        if(response.error == 0){
                        	if(response.numberFoundEggs < allEggs.length){
                        		var message = '<?php echo $this->getFoundEggsMessage(); ?>';
                        		message = message.replace("[eggs_found_count]", response.numberFoundEggs);
                        		message = message.replace("[eggs_all_count]", allEggs.length);
                        		$("#popup-modal-foundanegg .body").html('<div class="fnd">'+eggImage+'</div>'+'<p>'+message+'</p>');
                        		$("#popup-modal-foundanegg").show();
								$("#popup-eggs-back").show();
								currentElement.remove();
                        	}else{
                        		var message = '<?php echo $this->getFoundAllEggsMessage(); ?>';
                        		message = message.replace("[coupon_code]", couponCode);
                        		$("#popup-modal-foundalleggs .body").html('<div class="fnd">'+allEggsHtml+'</div>'+'<p>'+message+'</p>');

                        		$("#popup-modal-foundalleggs").show();
								$("#popup-eggs-back").show();
								currentElement.remove();
                        	}
                        }
		            },
		            error: function (response) {
		                console.log('error: '+response.error);
                        console.log('message: '+response.message);
                        console.log('numberFoundEggs: '+response.numberFoundEggs);
		            }
		        });
		        <?php
			} elseif ($this->isPublic()){
				?>
				$('#egg_id').val($(this).data('id'));
				$.ajax({
		            url: "/eastereggs/easteregg/saveeggcus/",
		            type: "POST",
		            data: $('form#saveeggcus').serialize(),
		            showLoader: true,
		            success: function (response) {
                        if(response.error == 0){
                        	if(response.numberFoundEggs < allEggs.length){
                        		var message = '<?php echo $this->getFoundEggsMessage(); ?>';
                        		message = message.replace("[eggs_found_count]", response.numberFoundEggs);
                        		message = message.replace("[eggs_all_count]", allEggs.length);
                        		$("#popup-modal-foundanegg .body").html('<div class="fnd">'+eggImage+'</div>'+'<p>'+message+'</p>');
                        		$("#popup-modal-foundanegg").show();
								$("#popup-eggs-back").show();
								currentElement.remove();
                        	}else{
                        		var message = '<?php echo $this->getFoundAllEggsMessage(); ?>';
                        		message = message.replace("[coupon_code]", couponCode);
                        		$("#popup-modal-foundalleggs .body").html('<div class="fnd">'+allEggsHtml+'</div>'+'<p>'+message+'</p>');
                        		$("#popup-modal-foundalleggs").show();
								$("#popup-eggs-back").show();
								currentElement.remove();
                        	}
                        }
		            },
		            error: function (response) {
		                console.log('error: '+response.error);
                        console.log('message: '+response.message);
                        console.log('numberFoundEggs: '+response.numberFoundEggs);
		            }
		        });
				<?php
			} else{
				?>
					$("#popup-modal-notloggedin").show();
					$("#popup-eggs-back").show();
				<?php
			}
			?>
		});

    }
);
</script>
<style type="text/css">
	#popup-eggs-back {
		position: fixed;
		top: 0;
		left: 0;
		width: 100%;
		height: 100%;
		background-color: rgba(0,0,0,0.6);
		z-index: 100;
	}
	.popup-eggs {
		width: 300px;
		display: inline-block;
		position: fixed;
		z-index: 101;
		top: calc(50% - 100px);
		left: calc(50% - 160px);
		background-color: #f9f9f9;
		border: 1px solid #9a9a9a;
		border-radius: 2px;
	}
	.popup-eggs .close {
		line-height: 10px;
		font-size: 14px;
		cursor: pointer;
		float: right;
		display: inline-block;
		width: 33px;
		margin: 10px;
		padding: 10px;
		text-align: center;
		background-color: #76c3fc;
		border-radius: 3px;
		border: 1px solid #3591de;
		color: white;
		font-weight: bold;
	}
	.popup-eggs .body {
		padding: 10px;
	}
	.popup-eggs .header {
		padding: 10px;
		font-size: 16px;
		background-color: #dedede;
		font-weight: bold;
	}
	.easter-cntr{
		cursor: pointer;
	}
	.easter-cntr img{
		
	}
	.popup-eggs .body .fnd {
		text-align: center;
	}
	.popup-eggs .body .fnd img {
		margin: 0 4px;
	}
</style>